name: dart_java_parser
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

dependencies:
  antlr4: ^4.13.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
