name: java_parser
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/KMayne/dart-java-parser

environment:
  sdk: ^3.2.4

dependencies:
  antlr4: ^4.13.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
